["github.com/davecgh/go-spew"]
  sumVersion = "v1.1.1"
  ["github.com/davecgh/go-spew".fetch]
    type = "git"
    url = "https://github.com/davecgh/go-spew"
    rev = "8991bc29aa16c548c550c7ff78260e27b9ab7c73"
    sha256 = "0hka6hmyvp701adzag2g26cxdj47g21x6jz4sc6jjz1mn59d474y"

["github.com/golang/protobuf"]
  sumVersion = "v1.2.0"
  ["github.com/golang/protobuf".fetch]
    type = "git"
    url = "https://github.com/golang/protobuf"
    rev = "aa810b61a9c79d51363740d207bb46cf8e620ed5"
    sha256 = "0kf4b59rcbb1cchfny2dm9jyznp8ri2hsb14n8iak1q8986xa0ab"

["github.com/google/go-github"]
  sumVersion = "v0.0.0-20170401000335-12363ffc1001"
  ["github.com/google/go-github".fetch]
    type = "git"
    url = "https://github.com/google/go-github"
    rev = "12363ffc10018c93407ebf303040586d55957271"
    sha256 = "02qdh3g71vwyzvc66lq77xkvw6yrbf6zn7mjf3xmm3kbij9xcmzw"

["github.com/google/go-querystring"]
  sumVersion = "v1.0.0"
  ["github.com/google/go-querystring".fetch]
    type = "git"
    url = "https://github.com/google/go-querystring"
    rev = "44c6ddd0a2342c386950e880b658017258da92fc"
    sha256 = "0xl12bqyvmn4xcnf8p9ksj9rmnr7s40pvppsdmy8n9bzw1db0iwz"

["github.com/hashicorp/go-cleanhttp"]
  sumVersion = "v0.5.1"
  ["github.com/hashicorp/go-cleanhttp".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-cleanhttp"
    rev = "eda1e5db218aad1db63ca4642c8906b26bcf2744"
    sha256 = "07kx3fhryqmaw3czacmm11qwx63js2q8cfq967vphk7xg9q377kk"

["github.com/hashicorp/go-hclog"]
  sumVersion = "v0.9.2"
  ["github.com/hashicorp/go-hclog".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-hclog"
    rev = "5ccdce08c75b6c7b37af61159f13f6a4f5e2e928"
    sha256 = "0pakba7rdkjgq50r79sbbpavymbyib77cy613wl734mpi30ywrxm"

["github.com/hashicorp/go-retryablehttp"]
  sumVersion = "v0.6.8"
  ["github.com/hashicorp/go-retryablehttp".fetch]
    type = "git"
    url = "https://github.com/hashicorp/go-retryablehttp"
    rev = "991b9d0a42d13014e3689dd49a94c02be01f4237"
    sha256 = "0522pgcpy0d0j642w19hdws83a2q9735gjync8ajl2k15hs5il6z"

["github.com/jordan-wright/email"]
  sumVersion = "v4.0.1-0.20200824153738-3f5bafa1cd84+incompatible"
  ["github.com/jordan-wright/email".fetch]
    type = "git"
    url = "https://github.com/jordan-wright/email"
    rev = "3f5bafa1cd84435706fe61e3189fcd9d1f7a3bf0"
    sha256 = "08ywrzyqims30gwrz0kfg6d3zp8mdy4kxw5cgrv7s6g0s0lhmjb6"

["github.com/pmezard/go-difflib"]
  sumVersion = "v1.0.0"
  ["github.com/pmezard/go-difflib".fetch]
    type = "git"
    url = "https://github.com/pmezard/go-difflib"
    rev = "792786c7400a136282c1664665ae0a8db921c6c2"
    sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw"

["github.com/stretchr/objx"]
  sumVersion = "v0.1.0"
  ["github.com/stretchr/objx".fetch]
    type = "git"
    url = "https://github.com/stretchr/objx"
    rev = "facf9a85c22f48d2f52f2380e4efce1768749a89"
    sha256 = "19ynspzjdynbi85xw06mh8ad5j0qa1vryvxjgvbnyrr8rbm4vd8w"

["github.com/stretchr/testify"]
  sumVersion = "v1.4.0"
  ["github.com/stretchr/testify".fetch]
    type = "git"
    url = "https://github.com/stretchr/testify"
    rev = "221dbe5ed46703ee255b1da0dec05086f5035f62"
    sha256 = "187i5g88sxfy4vxpm7dw1gwv29pa2qaq475lxrdh5livh69wqfjb"

["github.com/xanzy/go-gitlab"]
  sumVersion = "v0.50.2"
  ["github.com/xanzy/go-gitlab".fetch]
    type = "git"
    url = "https://github.com/xanzy/go-gitlab"
    rev = "3d61f208ea71858103c3e6ab0dc51c58e9954464"
    sha256 = "08z4cwq5vd25davs4yjiz7ih39fv559m3dmbx9yjwv0pa6sjs0rh"

["golang.org/x/crypto"]
  sumVersion = "v0.0.0-20200622213623-75b288015ac9"
  ["golang.org/x/crypto".fetch]
    type = "git"
    url = "https://go.googlesource.com/crypto"
    rev = "75b288015ac94e66e3d6715fb68a9b41bf046ec2"
    sha256 = "18vlncvvs11ds3zaaziqjlg5s2vcwi3496nn6qv7p0dp94j5pwa2"

["golang.org/x/net"]
  sumVersion = "v0.0.0-20201021035429-f5854403a974"
  ["golang.org/x/net".fetch]
    type = "git"
    url = "https://go.googlesource.com/net"
    rev = "f5854403a9740e74b2e9e725e6cd7c8a57711905"
    sha256 = "1vw63zpmhi337f3gc432x3wkib4j2ia8dy7if31wxwb9dgqvy222"

["golang.org/x/oauth2"]
  sumVersion = "v0.0.0-20181106182150-f42d05182288"
  ["golang.org/x/oauth2".fetch]
    type = "git"
    url = "https://go.googlesource.com/oauth2"
    rev = "f42d05182288abf10faef86d16c0d07b8d40ea2d"
    sha256 = "1cbwgr3f3wj84kjpldzzvrlkvlpp0jz8rgbj31xw8n3h502phwab"

["golang.org/x/sync"]
  sumVersion = "v0.0.0-20201020160332-67f06af15bc9"
  ["golang.org/x/sync".fetch]
    type = "git"
    url = "https://go.googlesource.com/sync"
    rev = "67f06af15bc961c363a7260195bcd53487529a21"
    sha256 = "093p4panc808ak5bamzz7m9nb0xxib7778jpnr6f0xkz1n4fzyw5"

["golang.org/x/sys"]
  sumVersion = "v0.0.0-20200930185726-fdedc70b468f"
  ["golang.org/x/sys".fetch]
    type = "git"
    url = "https://go.googlesource.com/sys"
    rev = "fdedc70b468f679c263a3ccaefc1faeed3239939"
    sha256 = "1njlfhjbvi4lxvjbq8zswrb0y0q4jd2p6x51h1q6vmyzi9af6869"

["golang.org/x/text"]
  sumVersion = "v0.3.3"
  ["golang.org/x/text".fetch]
    type = "git"
    url = "https://go.googlesource.com/text"
    rev = "23ae387dee1f90d29a23c0e87ee0b46038fbed0e"
    sha256 = "19pihqm3phyndmiw6i42pdv6z1rbvlqlsnhsyqf9gsnn0qnmqqlh"

["golang.org/x/time"]
  sumVersion = "v0.0.0-20191024005414-555d28b269f0"
  ["golang.org/x/time".fetch]
    type = "git"
    url = "https://go.googlesource.com/time"
    rev = "555d28b269f0569763d25dbe1a237ae74c6bcc82"
    sha256 = "1rhl4lyz030kwfsg63yk83yd3ivryv1afmzdz9sxbhcj84ym6h4r"

["golang.org/x/tools"]
  sumVersion = "v0.0.0-20180917221912-90fa682c2a6e"
  ["golang.org/x/tools".fetch]
    type = "git"
    url = "https://go.googlesource.com/tools"
    rev = "90fa682c2a6e6a37b3a1364ce2fe1d5e41af9d6d"
    sha256 = "03ic2xsy51jw9749wl7gszdbz99iijbd2bckgygl6cm9w5m364ak"

["google.golang.org/appengine"]
  sumVersion = "v1.3.0"
  ["google.golang.org/appengine".fetch]
    type = "git"
    url = "https://github.com/golang/appengine"
    rev = "4a4468ece617fc8205e99368fa2200e9d1fad421"
    sha256 = "13cyhqwmvc2nia4ssdwwdzscq52aj3z9zjikx17wk4kb0j8vr370"

["gopkg.in/check.v1"]
  sumVersion = "v0.0.0-20161208181325-20d25e280405"
  ["gopkg.in/check.v1".fetch]
    type = "git"
    url = "https://gopkg.in/check.v1"
    rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec"
    sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np"

["gopkg.in/yaml.v2"]
  sumVersion = "v2.2.2"
  ["gopkg.in/yaml.v2".fetch]
    type = "git"
    url = "https://gopkg.in/yaml.v2"
    rev = "51d6538a90f86fe93ac480b35f37b2be17fef232"
    sha256 = "01wj12jzsdqlnidpyjssmj0r4yavlqy7dwrg7adqd8dicjc4ncsa"
